declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_DATABASE_URL: string;
    NEXT_PUBLIC_MEASUREMENT_ID: string;
    NEXT_PUBLIC_GOOGLE_MAPS_API: string;
    NEXT_PUBLIC_ALGOLIA_APP_ID: string;
    NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY: string;
    NEXT_PUBLIC_SANITY_PROJECT_ID: string;
    NEXT_PUBLIC_SANITY_API_TOKEN: string;
    NEXT_PUBLIC_FACEBOOK_PIXEL_ID: string;
    NEXT_PUBLIC_BUILDER_PUBLIC_API_KEY: string;
    NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: string;
    FIREBASE_ADMIN_PROJECT_ID: string;
    FIREBASE_ADMIN_CLIENT_EMAIL: string;
    FIREBASE_ADMIN_PRIVATE_KEY: string;
    FIREBASE_ADMIN_STORAGE_BUCKET: string;
    SESSION_PASSWORD: string;
    SEND_GRID_API: string;
    SMTP_USER: string;
    SMTP_PASSWORD: string;
    ALGOLIA_APPLICATION_ID: string;
    ALGOLIA_ADMIN_API_KEY: string;
    WHATSAPP_ACCSESS_TOKEN: string;
    WHATSAPP_PHONE_NUMBER_ID: string;
    WHATSAPP_RECEIPENT_PHONE_NUMBER: string;
  }
}
